import { createRequire } from 'node:module'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const ts = require('typescript')
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = join(root, 'src')
const distDir = join(root, 'dist')

function moduleId(path) {
  return relative(srcDir, path).split(sep).join('/').replace(/\.ts$/, '')
}

function sourceFiles(entry) {
  const seen = new Set()
  const visit = path => {
    path = resolve(path)
    if (seen.has(path)) return
    seen.add(path)
    const source = readFileSync(path, 'utf8')
    for (const imported of ts.preProcessFile(source).importedFiles) {
      if (!imported.fileName.startsWith('.')) continue
      visit(resolve(dirname(path), imported.fileName.endsWith('.ts') ? imported.fileName : `${imported.fileName}.ts`))
    }
  }
  visit(join(srcDir, `${entry}.ts`))
  return [...seen]
}

function transpile(path) {
  const source = readFileSync(path, 'utf8')
  const result = ts.transpileModule(source, {
    fileName: path,
    reportDiagnostics: true,
    compilerOptions: {
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.CommonJS,
      strict: true,
      esModuleInterop: true,
      removeComments: false,
      sourceMap: false,
    },
  })
  const errors = (result.diagnostics ?? []).filter(item => item.category === ts.DiagnosticCategory.Error)
  if (errors.length) {
    const host = { getCanonicalFileName: name => name, getCurrentDirectory: () => root, getNewLine: () => '\n' }
    throw new Error(ts.formatDiagnostics(errors, host))
  }
  return result.outputText
}

function bundle(entry, output, frontend = false) {
  const modules = sourceFiles(entry)
    .map(path => [moduleId(path), transpile(path)])
    .sort(([a], [b]) => a.localeCompare(b))

  const registry = modules.map(([id, code]) =>
    `${JSON.stringify(id)}: function(require, module, exports) {\n${code}\n}`
  ).join(',\n')

  const footer = frontend
    ? `const __entry = __load(${JSON.stringify(entry)});\nexport const setup = __entry.setup;\n`
    : `__load(${JSON.stringify(entry)});\n`

  const outputText = `// Shutter 1.1.0 — generated by scripts/build.mjs\nconst __modules = {\n${registry}\n};\nconst __cache = Object.create(null);\nfunction __resolve(from, request) {\n  if (!request.startsWith('.')) throw new Error('Unsupported external runtime import: ' + request);\n  const base = from.split('/');\n  base.pop();\n  for (const part of request.split('/')) {\n    if (!part || part === '.') continue;\n    if (part === '..') base.pop();\n    else base.push(part);\n  }\n  return base.join('/').replace(/\\.js$/, '');\n}\nfunction __load(id) {\n  if (__cache[id]) return __cache[id].exports;\n  const factory = __modules[id];\n  if (!factory) throw new Error('Unknown bundled module: ' + id);\n  const module = { exports: {} };\n  __cache[id] = module;\n  factory(request => __load(__resolve(id, request)), module, module.exports);\n  return module.exports;\n}\n${footer}`

  mkdirSync(distDir, { recursive: true })
  writeFileSync(join(distDir, output), outputText)
  console.log(`Built ${output} (${Buffer.byteLength(outputText).toLocaleString()} bytes)`)
}

bundle('backend', 'backend.js')
bundle('frontend', 'frontend.js', true)
